services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - ${RABBITMQ_EXT_PORT}:5672     # AMQP порт
      - ${RABBITMQ_UI_EXT_PORT}:15672 # Веб-интерфейс RabbitMQ
    networks:
      - crypto_network
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

networks:
  crypto_network:
    driver: bridge
