services:
  api-gateway-app:
    build:
      context: ../../  # Контекст сборки теперь на 2 уровня выше, в services
      dockerfile: common/laravel/Dockerfile  # Путь к Dockerfile внутри папки common/laravel\
      args:
        PROJECT_NAME: api_gateway
    container_name: api-gateway-app
    volumes:
      - ../source:/var/www  # Монтируем исходный код Laravel в контейнер
    networks:
      - crypto_network
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_QUEUE_USERS=users
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
      - LOGSTASH_PORT=${LOGSTASH_PORT}

  api-gateway-nginx:
    image: nginx:alpine
    container_name: api-gateway-nginx
    restart: unless-stopped
    ports:
      - ${NGINX_EXT_PORT}:80
    volumes:
      - ../source:/var/www  # Монтируем исходный код Laravel в контейнер
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge
