services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - ${REDIS_EXT_PORT}:6379
    volumes:
      - ./data:/data  # Прокидываем volume для хранения данных
    networks:
      - crypto_network
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: 6379

networks:
  crypto_network:
    driver: bridge
